/**
 * 주방 자동화 제품군별 라인업 (군당 3 SKU + 미선택)
 * 가격·월비는 시뮬레이션용 대표값
 */

export const EQUIPMENT_CATEGORIES = [
  {
    id: 'dishwasher',
    name: '식기세척',
    desc: '랙·도어형·컨베어 등 업소용 세척 설비로 설거지 인력·시간을 줄입니다.',
    icon: '🫧',
    options: [
      {
        id: 'dishwasher_rack_s',
        name: '소형 랙 컨베어 세척기',
        manufacturer: 'Hobart / 국산 유사급',
        price: 8200000,
        priceNote: '소규모 홀·브런치 적합',
        monthlyCost: 110000,
        powerCostPerMonth: 52000,
        staffEquiv: 0.35,
        throughputPts: 5,
        wastePts: 3,
      },
      {
        id: 'dishwasher_door_m',
        name: '도어형 랙 세척기(중형)',
        manufacturer: 'Winterhalter / Hobart급',
        price: 15800000,
        priceNote: '중형 이상 매장 표준',
        monthlyCost: 185000,
        powerCostPerMonth: 68000,
        staffEquiv: 0.55,
        throughputPts: 7,
        wastePts: 4,
      },
      {
        id: 'dishwasher_conv_l',
        name: '고속 컨베어 세척 라인',
        manufacturer: '업소용 대형 라인',
        price: 26800000,
        priceNote: '뷔페·단체·고회전 매장',
        monthlyCost: 260000,
        powerCostPerMonth: 95000,
        staffEquiv: 0.85,
        throughputPts: 9,
        wastePts: 5,
      },
    ],
  },
  {
    id: 'stirCook',
    name: '볶음·조리 자동화',
    desc: '자동 웍·다구 조리·면 삶기 등으로 조리 동선과 화력 관리를 표준화합니다.',
    icon: '🔥',
    options: [
      {
        id: 'stir_single',
        name: '자동 웍·볶음 1구 스테이션',
        manufacturer: '상업용 자동조리 모듈',
        price: 7200000,
        priceNote: '볶음·덮밥 중심 소형 주방',
        monthlyCost: 70000,
        powerCostPerMonth: 85000,
        staffEquiv: 0.3,
        throughputPts: 8,
        wastePts: 5,
      },
      {
        id: 'stir_multi',
        name: '다구 자동 조리 스테이션',
        manufacturer: '멀티존 인덕션·프로그램 연동',
        price: 19800000,
        priceNote: '다품종 동시 조리',
        monthlyCost: 140000,
        powerCostPerMonth: 120000,
        staffEquiv: 0.55,
        throughputPts: 12,
        wastePts: 7,
      },
      {
        id: 'stir_noodle',
        name: '면·파스타 자동 삶기·데우기',
        manufacturer: '면 라인 전용 모듈',
        price: 11200000,
        priceNote: '라멘·분식·파스타 전문',
        monthlyCost: 85000,
        powerCostPerMonth: 95000,
        staffEquiv: 0.4,
        throughputPts: 10,
        wastePts: 4,
      },
    ],
  },
  {
    id: 'prep',
    name: '재료 손질',
    desc: '세척·슬라이스·전처리 자동화로 준비 시간과 재료 손실을 줄입니다.',
    icon: '🥬',
    options: [
      {
        id: 'prep_wash',
        name: '채소 자동 세척·건조기',
        manufacturer: 'HORECA용 전처리',
        price: 8900000,
        priceNote: '샐러드·채소 다량 사용 매장',
        monthlyCost: 65000,
        powerCostPerMonth: 48000,
        staffEquiv: 0.35,
        throughputPts: 6,
        wastePts: 8,
      },
      {
        id: 'prep_slice',
        name: '슬라이서·다지기 올인원',
        manufacturer: '상업용 컷팅 스테이션',
        price: 6200000,
        priceNote: '배치·육류·채소 공용',
        monthlyCost: 45000,
        powerCostPerMonth: 35000,
        staffEquiv: 0.25,
        throughputPts: 5,
        wastePts: 6,
      },
      {
        id: 'prep_vac',
        name: '진공·브라인 전처리 라인',
        manufacturer: '저온·숙성 연동',
        price: 14800000,
        priceNote: '정육·양식·프리미엄 한식',
        monthlyCost: 90000,
        powerCostPerMonth: 55000,
        staffEquiv: 0.3,
        throughputPts: 7,
        wastePts: 10,
      },
    ],
  },
  {
    id: 'fryer',
    name: '튀김·프라이',
    desc: '압력·오픈·인덕션 프라이로 온도·시간을 맞춰 조리 편차와 오일 손실을 줄입니다.',
    icon: '🍟',
    options: [
      {
        id: 'fry_open',
        name: '오픈 프라이어 더블 탱크',
        manufacturer: 'Pitco / 국산 유사급',
        price: 4800000,
        priceNote: '치킨·감자·분식',
        monthlyCost: 55000,
        powerCostPerMonth: 72000,
        staffEquiv: 0.2,
        throughputPts: 9,
        wastePts: 6,
      },
      {
        id: 'fry_pressure',
        name: '압력 프라이어',
        manufacturer: 'Henny Penny급',
        price: 11800000,
        priceNote: '고속·정온 튀김',
        monthlyCost: 95000,
        powerCostPerMonth: 88000,
        staffEquiv: 0.35,
        throughputPts: 11,
        wastePts: 8,
      },
      {
        id: 'fry_induction',
        name: '인덕션 프라이존 + 오일 관리',
        manufacturer: '인덕션 프라이 모듈',
        price: 9200000,
        priceNote: '연기·열관리 개선',
        monthlyCost: 70000,
        powerCostPerMonth: 78000,
        staffEquiv: 0.25,
        throughputPts: 8,
        wastePts: 7,
      },
    ],
  },
  {
    id: 'combi',
    name: '콤비·만능 오븐',
    desc: '증기·대류·혼합으로 굽기·찜·보온을 한 기기에서 처리합니다.',
    icon: '♨️',
    options: [
      {
        id: 'combi_small',
        name: '소형 콤비 (6~10단)',
        manufacturer: 'Rational / MKN급 소형',
        price: 18500000,
        priceNote: '소·중형 매장',
        monthlyCost: 160000,
        powerCostPerMonth: 82000,
        staffEquiv: 0.4,
        throughputPts: 10,
        wastePts: 9,
      },
      {
        id: 'combi_pro',
        name: 'iCombi Pro급 단일 대형',
        manufacturer: 'Rational 등',
        price: 36800000,
        priceNote: '고회전·다품종',
        monthlyCost: 280000,
        powerCostPerMonth: 105000,
        staffEquiv: 0.65,
        throughputPts: 14,
        wastePts: 12,
      },
      {
        id: 'combi_stack',
        name: '콤비 스택 2단',
        manufacturer: '듀얼 스택 구성',
        price: 62000000,
        priceNote: '뷔페·대형 브랜드',
        monthlyCost: 420000,
        powerCostPerMonth: 155000,
        staffEquiv: 0.9,
        throughputPts: 16,
        wastePts: 13,
      },
    ],
  },
];

/** 카테고리 id → 빈 선택 객체 */
export function createEmptyKitchenSelections() {
  return Object.fromEntries(EQUIPMENT_CATEGORIES.map((c) => [c.id, null]));
}

export function findOptionByProductId(productId) {
  for (const cat of EQUIPMENT_CATEGORIES) {
    const opt = cat.options.find((o) => o.id === productId);
    if (opt) return { category: cat, option: opt };
  }
  return null;
}
